# Generated by Django 3.0.8 on 2020-07-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_type',
            field=models.CharField(choices=[('ph', 'Phone'), ('lp', 'Laptop'), ('fr', 'Fridge'), ('st', 'Stove')], default='None', max_length=2),
        ),
    ]
